name: "Build and publish"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  generate-matrix:
    name: "Generate matrix"
    runs-on: ubuntu-latest

    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Test
        run: |
          if [ $GITHUB_BASE_REF ]; then
            # Pull Request
            echo Pull
            echo ${{ github.event.pull_request.base.ref }}
            echo ${{ github.event.pull_request.base.sha }}
          else
            # Push
            echo Push
            echo ${{ github.event.base_ref }}
            echo ${{ github.event.before }}
          fi

      - name: Python
        run: |
          if [ $GITHUB_BASE_REF ]; then
            echo Pull
            export PREVIOUS_SHA="origin/$GITHUB_BASE_REF"
          else
            echo Push
            export PREVIOUS_SHA="${{ github.event.before }}"
          fi
          export CURRENT_SHA="$GITHUB_SHA"
          python env.py

      - name: Dump
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"